# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='visibility',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='能见度'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tide_level',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='潮位'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='lamp_device',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='灯器'),
        ),
    ]
