# Generated by Django 5.1.4 on 2026-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='lantern',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='灯器'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tide_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='潮位'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='visibility',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='能见度'),
        ),
    ]
